---
title: "sAP Globalization Quality dataset sensit on A"
author: "Guillaume Barbalat"
date: "17/04/2022"
output: html_document
---

# load data and packages
```{r warning=FALSE, message=FALSE, echo=FALSE, results=FALSE}
#read_clean.R, which produces a final_matrix data.frame
#check out lines 18-28
rm(list=ls())
getwd()
library(dplyr)
library(lmtp)
library(table1)
library(ggplot2)
library(tidyr)

sensit="_sensit_A"# 
loaded_data=load(file=paste0("results_lmtp_Quality",sensit,".RData"))
psi_results_data=psi_results_data

idx_psi1=1;idx_psi2=2;idx_psi3=3;idx_psi4=4;
idx_results_MSM_categ=5
idx_matrix=6

list_trt=c("KOFTrGIdf",	"KOFTrGIdj", "KOFFiGIdf",	"KOFFiGIdj",	
           "KOFIpGIdf",	"KOFIpGIdj", "KOFInGIdf",	"KOFInGIdj", "KOFCuGIdf",	"KOFCuGIdj",
           "KOFPoGIdf",	"KOFPoGIdj")
```

# loop through MBD
``` {r echo=FALSE, warning=FALSE, message=FALSE}
for (i in 1:length(psi_results_data)) {

  
  psi_1=psi_results_data[[i]][[idx_psi1]]
  psi_2=psi_results_data[[i]][[idx_psi2]]
  psi_3=psi_results_data[[i]][[idx_psi3]]
  psi_4=psi_results_data[[i]][[idx_psi4]]
  
  results_MSM_categ=psi_results_data[[i]][[idx_results_MSM_categ]]

  final_matrix_quality_2019=psi_results_data[[i]][[idx_matrix]]
  
  print(list_trt[i])

 

# raw results
print(results_MSM_categ)



#### Dx

weights_hist <- function(psi_1,psi_2,psi_3,psi_4) {
weights=vector(length=nrow(final_matrix_quality_2019))
weights[psi_1$density_ratios!=0]=psi_1$density_ratios[psi_1$density_ratios!=0]
weights[psi_2$density_ratios!=0]=psi_2$density_ratios[psi_2$density_ratios!=0]
weights[psi_3$density_ratios!=0]=psi_3$density_ratios[psi_3$density_ratios!=0]
weights[psi_4$density_ratios!=0]=psi_4$density_ratios[psi_4$density_ratios!=0]
return(weights)
}
weights<-weights_hist(psi_1=psi_1,
                      psi_2=psi_2,
                      psi_3=psi_3,
                      psi_4=psi_4)
hist(weights, main="Histogram of weights (Trimming weights > 0.999)",xlab=NULL)
print(summary(weights))



    
 
### SL coeff
coeff_pullout<-function(coeff_multiple) {
  tmp=do.call(c,coeff_multiple);all_idx=do.call(cbind,tmp);
  data.frame(algo=rownames(all_idx),
                          mean=rowMeans(all_idx))
  }
# print(coeff_pullout(psi_1$weights_m))
# print(coeff_pullout(psi_1$weights_r))
# print(coeff_pullout(psi_1$weights_m))
# print(coeff_pullout(psi_2$weights_r))
# print(coeff_pullout(psi_3$weights_m))
# print(coeff_pullout(psi_3$weights_r))
# print(coeff_pullout(psi_4$weights_m))
# print(coeff_pullout(psi_4$weights_r))


}

```